server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          public-client:
            registration:
              client-id: "public-linkrew"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://127.0.0.1:3000"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
            require-proof-key: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/spring-auth?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: username
    password: password